version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ../sofia/mongo_data:/data/db
  mongodb1:
    image: mongo:5.0
    ports:
      - "28105:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sofia
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ../sofia/mongo_data1:/data/db
networks:
  default:
    external:
      name: proxy
